# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.v1_process_metadata import V1ProcessMetadata  # noqa: F401,E501
from swagger_server import util


class V1CreateProcessMetadataResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, created_md: V1ProcessMetadata=None):  # noqa: E501
        """V1CreateProcessMetadataResponse - a model defined in Swagger

        :param created_md: The created_md of this V1CreateProcessMetadataResponse.  # noqa: E501
        :type created_md: V1ProcessMetadata
        """
        self.swagger_types = {
            'created_md': V1ProcessMetadata
        }

        self.attribute_map = {
            'created_md': 'createdMd'
        }
        self._created_md = created_md

    @classmethod
    def from_dict(cls, dikt) -> 'V1CreateProcessMetadataResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v1CreateProcessMetadataResponse of this V1CreateProcessMetadataResponse.  # noqa: E501
        :rtype: V1CreateProcessMetadataResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created_md(self) -> V1ProcessMetadata:
        """Gets the created_md of this V1CreateProcessMetadataResponse.


        :return: The created_md of this V1CreateProcessMetadataResponse.
        :rtype: V1ProcessMetadata
        """
        return self._created_md

    @created_md.setter
    def created_md(self, created_md: V1ProcessMetadata):
        """Sets the created_md of this V1CreateProcessMetadataResponse.


        :param created_md: The created_md of this V1CreateProcessMetadataResponse.
        :type created_md: V1ProcessMetadata
        """

        self._created_md = created_md
