# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.v1_process_metadata import V1ProcessMetadata  # noqa: F401,E501
from swagger_server.models.v1_process_report_generation_status import V1ProcessReportGenerationStatus  # noqa: F401,E501
from swagger_server import util


class V1ListProcessMetadataResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, mds: List[V1ProcessMetadata]=None, report_status: List[V1ProcessReportGenerationStatus]=None):  # noqa: E501
        """V1ListProcessMetadataResponse - a model defined in Swagger

        :param mds: The mds of this V1ListProcessMetadataResponse.  # noqa: E501
        :type mds: List[V1ProcessMetadata]
        :param report_status: The report_status of this V1ListProcessMetadataResponse.  # noqa: E501
        :type report_status: List[V1ProcessReportGenerationStatus]
        """
        self.swagger_types = {
            'mds': List[V1ProcessMetadata],
            'report_status': List[V1ProcessReportGenerationStatus]
        }

        self.attribute_map = {
            'mds': 'mds',
            'report_status': 'reportStatus'
        }
        self._mds = mds
        self._report_status = report_status

    @classmethod
    def from_dict(cls, dikt) -> 'V1ListProcessMetadataResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v1ListProcessMetadataResponse of this V1ListProcessMetadataResponse.  # noqa: E501
        :rtype: V1ListProcessMetadataResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mds(self) -> List[V1ProcessMetadata]:
        """Gets the mds of this V1ListProcessMetadataResponse.


        :return: The mds of this V1ListProcessMetadataResponse.
        :rtype: List[V1ProcessMetadata]
        """
        return self._mds

    @mds.setter
    def mds(self, mds: List[V1ProcessMetadata]):
        """Sets the mds of this V1ListProcessMetadataResponse.


        :param mds: The mds of this V1ListProcessMetadataResponse.
        :type mds: List[V1ProcessMetadata]
        """

        self._mds = mds

    @property
    def report_status(self) -> List[V1ProcessReportGenerationStatus]:
        """Gets the report_status of this V1ListProcessMetadataResponse.


        :return: The report_status of this V1ListProcessMetadataResponse.
        :rtype: List[V1ProcessReportGenerationStatus]
        """
        return self._report_status

    @report_status.setter
    def report_status(self, report_status: List[V1ProcessReportGenerationStatus]):
        """Sets the report_status of this V1ListProcessMetadataResponse.


        :param report_status: The report_status of this V1ListProcessMetadataResponse.
        :type report_status: List[V1ProcessReportGenerationStatus]
        """

        self._report_status = report_status
