# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class V1ProcessMap(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, process_map: str=None):  # noqa: E501
        """V1ProcessMap - a model defined in Swagger

        :param process_map: The process_map of this V1ProcessMap.  # noqa: E501
        :type process_map: str
        """
        self.swagger_types = {
            'process_map': str
        }

        self.attribute_map = {
            'process_map': 'processMap'
        }
        self._process_map = process_map

    @classmethod
    def from_dict(cls, dikt) -> 'V1ProcessMap':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v1ProcessMap of this V1ProcessMap.  # noqa: E501
        :rtype: V1ProcessMap
        """
        return util.deserialize_model(dikt, cls)

    @property
    def process_map(self) -> str:
        """Gets the process_map of this V1ProcessMap.


        :return: The process_map of this V1ProcessMap.
        :rtype: str
        """
        return self._process_map

    @process_map.setter
    def process_map(self, process_map: str):
        """Sets the process_map of this V1ProcessMap.


        :param process_map: The process_map of this V1ProcessMap.
        :type process_map: str
        """

        self._process_map = process_map
