# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.v1_report_generation_status import V1ReportGenerationStatus  # noqa: F401,E501
from swagger_server import util


class V1ProcessReportGenerationStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, process_id: str=None, status: V1ReportGenerationStatus=None, time_remaining: str=None):  # noqa: E501
        """V1ProcessReportGenerationStatus - a model defined in Swagger

        :param process_id: The process_id of this V1ProcessReportGenerationStatus.  # noqa: E501
        :type process_id: str
        :param status: The status of this V1ProcessReportGenerationStatus.  # noqa: E501
        :type status: V1ReportGenerationStatus
        :param time_remaining: The time_remaining of this V1ProcessReportGenerationStatus.  # noqa: E501
        :type time_remaining: str
        """
        self.swagger_types = {
            'process_id': str,
            'status': V1ReportGenerationStatus,
            'time_remaining': str
        }

        self.attribute_map = {
            'process_id': 'processId',
            'status': 'status',
            'time_remaining': 'timeRemaining'
        }
        self._process_id = process_id
        self._status = status
        self._time_remaining = time_remaining

    @classmethod
    def from_dict(cls, dikt) -> 'V1ProcessReportGenerationStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v1ProcessReportGenerationStatus of this V1ProcessReportGenerationStatus.  # noqa: E501
        :rtype: V1ProcessReportGenerationStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def process_id(self) -> str:
        """Gets the process_id of this V1ProcessReportGenerationStatus.


        :return: The process_id of this V1ProcessReportGenerationStatus.
        :rtype: str
        """
        return self._process_id

    @process_id.setter
    def process_id(self, process_id: str):
        """Sets the process_id of this V1ProcessReportGenerationStatus.


        :param process_id: The process_id of this V1ProcessReportGenerationStatus.
        :type process_id: str
        """

        self._process_id = process_id

    @property
    def status(self) -> V1ReportGenerationStatus:
        """Gets the status of this V1ProcessReportGenerationStatus.


        :return: The status of this V1ProcessReportGenerationStatus.
        :rtype: V1ReportGenerationStatus
        """
        return self._status

    @status.setter
    def status(self, status: V1ReportGenerationStatus):
        """Sets the status of this V1ProcessReportGenerationStatus.


        :param status: The status of this V1ProcessReportGenerationStatus.
        :type status: V1ReportGenerationStatus
        """

        self._status = status

    @property
    def time_remaining(self) -> str:
        """Gets the time_remaining of this V1ProcessReportGenerationStatus.


        :return: The time_remaining of this V1ProcessReportGenerationStatus.
        :rtype: str
        """
        return self._time_remaining

    @time_remaining.setter
    def time_remaining(self, time_remaining: str):
        """Sets the time_remaining of this V1ProcessReportGenerationStatus.


        :param time_remaining: The time_remaining of this V1ProcessReportGenerationStatus.
        :type time_remaining: str
        """

        self._time_remaining = time_remaining
