# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class V1ReportGenerationStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    UNSPECIFIED = "REPORT_GENERATION_STATUS_UNSPECIFIED"
    IN_PROGRESS = "REPORT_GENERATION_STATUS_IN_PROGRESS"
    DONE = "REPORT_GENERATION_STATUS_DONE"
    def __init__(self):  # noqa: E501
        """V1ReportGenerationStatus - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'V1ReportGenerationStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v1ReportGenerationStatus of this V1ReportGenerationStatus.  # noqa: E501
        :rtype: V1ReportGenerationStatus
        """
        return util.deserialize_model(dikt, cls)
