# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.v1_process_metadata import V1ProcessMetadata  # noqa: F401,E501
from swagger_server import util


class V1UpdateProcessMetadataResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, updated_md: V1ProcessMetadata=None):  # noqa: E501
        """V1UpdateProcessMetadataResponse - a model defined in Swagger

        :param updated_md: The updated_md of this V1UpdateProcessMetadataResponse.  # noqa: E501
        :type updated_md: V1ProcessMetadata
        """
        self.swagger_types = {
            'updated_md': V1ProcessMetadata
        }

        self.attribute_map = {
            'updated_md': 'updatedMd'
        }
        self._updated_md = updated_md

    @classmethod
    def from_dict(cls, dikt) -> 'V1UpdateProcessMetadataResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v1UpdateProcessMetadataResponse of this V1UpdateProcessMetadataResponse.  # noqa: E501
        :rtype: V1UpdateProcessMetadataResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def updated_md(self) -> V1ProcessMetadata:
        """Gets the updated_md of this V1UpdateProcessMetadataResponse.


        :return: The updated_md of this V1UpdateProcessMetadataResponse.
        :rtype: V1ProcessMetadata
        """
        return self._updated_md

    @updated_md.setter
    def updated_md(self, updated_md: V1ProcessMetadata):
        """Sets the updated_md of this V1UpdateProcessMetadataResponse.


        :param updated_md: The updated_md of this V1UpdateProcessMetadataResponse.
        :type updated_md: V1ProcessMetadata
        """

        self._updated_md = updated_md
